### ISSUE TITLE
Use Bray-Curtis for taxonomic similarity visualisation

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/edna-tool-ui#2]
https://github.com/nickpoorman/bray-curtis

**Comment by tobiasgf** [comment]
If it is easy, then I suggest a data-transformation before calculating the B-C.
There are elaborate ways (hellinger transformation, etc), but taking the fourth root of each value (x^0.25) is a quick and acceptable solution.
Will scale the abundances so that the highly abundant read have less (but still more) impact: 1 = 1, 10 ≈ 1.8, 100 ≈ 3.2, 1000 ≈ 5.6, 10000 = 10, .....
